### ISSUE TITLE
Bug in slicing?

### ISSUE THREAD

**Issue by Oktai15** [AnotherSamWilson/fastshap#2]
Should we use `shap_values[:, :-2, :]` instead of:

https://github.com/AnotherSamWilson/fastshap/blob/c0cf5c37fe2bdabebc0a0660a4f0757ccd857d72/fastshap/KernelExplainer.py#L416 ?

@AnotherSamWilson

**Comment by samFarrellDay** [comment]
This is meant to be an adjustment to the last variable in case the contributions don't _quite_ add up to the prediction. This adjustment should always be small. If you are seeing any adjustments here that aren't small, can you provide an example?

[Here is a link to the corresponding line in the original shap kernel implementation.](https://github.com/slundberg/shap/blob/master/shap/explainers/_kernel.py#L602)

**Comment by Oktai15** [comment]
I got it, thanks!
