### ISSUE TITLE
Install fails due to sklearn dependency

### ISSUE THREAD

**Issue by Zahlii** [AnotherSamWilson/fastshap#6]
11:01:39    × python setup.py egg_info did not run successfully.
11:01:39    │ exit code: 1
11:01:39    ╰─> [18 lines of output]
11:01:39        The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
11:01:39        rather than 'sklearn' for pip commands.
11:01:39        
11:01:39        Here is how to fix this error in the main use cases:
11:01:39        - use 'pip install scikit-learn' rather than 'pip install sklearn'
11:01:39        - replace 'sklearn' by 'scikit-learn' in your pip requirements files
11:01:39          (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
11:01:39        - if the 'sklearn' package is used by one of your dependencies,
11:01:39          it would be great if you take some time to track which package uses
11:01:39          'sklearn' instead of 'scikit-learn' and report it to their issue tracker
11:01:39        - as a last resort, set the environment variable
11:01:39          SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
11:01:39        
11:01:39        More information is available at
11:01:39        https://github.com/scikit-learn/sklearn-pypi-package
11:01:39        
11:01:39        If the previous advice does not cover your use case, feel free to report it at
11:01:39        https://github.com/scikit-learn/sklearn-pypi-package/issues/new
11:01:39        [end of output]

**Comment by gradientsky** [comment]
Would you mind pushing a new release out including this change? pypi version still vends with `sklearn` dependency.
